parent_cfg: configs/mvsgs/dtu_pretrain.yaml

train_dataset_module: lib.datasets.colmap.mvsgs
test_dataset_module: lib.datasets.colmap.mvsgs

mvsgs:
    eval_center: True
    reweighting: True
    scale_factor: 12
    memory_saving: True  # Add this to enable memory optimizations
    cas_config:
        render_if: [False, True]
        volume_planes: [16, 8]  # Reduced from [64, 8]
        volume_scale: [0.125, 0.5]
        im_feat_scale: [0.25, 0.5]
        im_ibr_scale: [0.25, 1.]
        render_scale: [0.25, 1.0]

train_dataset:
    data_root: 'examples'
    split: 'train'
    input_h_w: [512, 384]  # Back to original size to save memory
    input_ratio: 1.
    scene: ''

test_dataset:
    data_root: 'examples'
    split: 'test'
    input_h_w: [512, 384]
    scene: ''